apiVersion: {{ include "ingressversion" . }}
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    nginx.ingress.kubernetes.io/auth-secret: {{ .Chart.Name }}-basic-auth
    nginx.ingress.kubernetes.io/auth-type: basic
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  tls:
  {{- range .Values.ingress.hosts }}
  - secretName: {{ required ".secretName is required" .secretName }}
    hosts:
    - {{ required ".hostName is required" .hostName }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ required ".hostName is required" .hostName }}
    http:
      paths:
      - path: /
    {{- if semverCompare ">= 1.19-0" .Capabilities.KubeVersion.GitVersion }}
        pathType: Prefix
        backend:
          service:
            name: prometheus-web
            port:
              number: 80
    {{- else }}
        backend:
          serviceName: prometheus-web
          servicePort: 80
    {{- end }}
  {{- end }}
